---
- name: /etc/rc.conf | zfs_enable
  sysrc:
    name: zfs_enable
    value: "YES"

- name: /etc/sysctl.conf | vfs.zfs.min_auto_ashift
  sysrc:
    name: vfs.zfs.min_auto_ashift
    value: "12"
    dest: /etc/sysctl.conf
