---
- name: /etc/rc.conf | zfs_enable
  sysrc:
    name: zfs_enable
    value: "YES"

- name: /etc/sysctl.conf | vfs.zfs.min_auto_ashift
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^([\s]*)\#?([\s]*)vfs\.zfs\.min_auto_ashift([\s]*)='
    line: 'vfs.zfs.min_auto_ashift="12"'
    owner: root
    group: wheel
    mode: 0644
