---
# NOTE(seanc@): The copy module with force=no and content='' is the idiomatic
# way provided by ansible to make sure a file exists.
- name: periodic | log files
  copy:
    dest: "/var/log/periodic-{{ item }}.log"
    owner: root
    group: wheel
    force: no
    content: ''
    mode: 0640
  with_items:
    - hourly
    - daily
    - weekly
    - monthly

- name: /etc/periodic.conf
  copy:
    dest: /etc/periodic.conf
    owner: root
    group: wheel
    force: no
    content: ''
    mode: 0644

- name: /etc/periodic.conf | periodic output
  lineinfile:
    dest: /etc/periodic.conf
    regexp: '^([\s]*)[\#]?([\s]*){{ item }}_output="/var/log/periodic-{{ item }}.log"'
    line: '{{ item }}_output="/var/log/periodic-{{ item }}.log"'
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - hourly
    - daily
    - weekly
    - monthly
