---
- name: /etc/rc.conf | powerd_enable
  sysrc:
    name: powerd_enable
    value: "YES"
  notify:
    - powerd start

- name: /etc/rc.conf | powerd_flags
  sysrc:
    name: powerd_flags
    value: "-a hiadaptive -b minimum"
  notify:
    - powerd restart
