---
- name: kld | drm
  kld: name=drm load=yes boot=yes

- name: drm2 | kldload
  kld: name=drm2 load=yes boot=yes

# NOTE(seanc@, 2015-06-14): The boot value for drm.i915.prefault_disable is
# uninitialized by the kernel, explicitly set to 0 at boot time.
#
# NOTE(seanc@): enable_rc6 tunables is defined in
# sys/dev/drm2/i915/i915_drv.c
- name: drm2 | /boot/loader.conf | defaults
  lineinfile:
    dest: /boot/loader.conf
    regexp: '^([\s]*){{ item.k }}([\s]*)='
    line: '{{ item.k }}="{{ item.v }}"'
    owner: root
    group: wheel
    mode: 0644
  with_items:
    - { k: 'drm.i915.intel_iommu_enabled',    v:  '0' }
    - { k: 'drm.i915.intel_iommu_gfx_mapped', v:  '0' }
    - { k: 'drm.i915.lvds_downclock',         v:  '0' }
    - { k: 'drm.i915.prefault_disable',       v:  '0' }
    - { k: 'drm.i915.semaphores',             v: '-1' }
    - { k: 'drm.i915.try_reset',              v:  '1' }

# NOTE(seanc@): The following should be removed from loader.conf in order to
# have suspend/resume work from X11 on a T420.  Note, suspend/resume doesn't
# work from non-X11.
- name: drm2 | /boot/loader.conf | disable rc6
  lineinfile:
    dest: /boot/loader.conf
    regexp: '^[\s]*[\#]?[\s]*drm\.i915\.enable_rc6([\s]*)='
    owner: root
    group: wheel
    mode: 0644
    state: absent
  when: enable_rc6 == False
