---
- name: /etc/sysctl.conf | hw.acpi.lid_switch_state
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^([\s]*)[\#]?([\s]*)hw\.acpi\.lid_switch_state([\s]*)='
    line: 'hw.acpi.lid_switch_state="S3"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

- name: /etc/sysctl.conf | hw.acpi.power_button_state
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^([\s]*)[\#]?([\s]*)hw\.acpi\.power_button_state([\s]*)='
    line: 'hw.acpi.power_button_state="S5"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

# NOTE(seanc@): Need to test if this works before removing state=absent
- name: /etc/sysctl.conf | hw.acpi.reset_video
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^([\s]*)[\#]?([\s]*)hw\.acpi\.reset_video([\s]*)='
    line: 'hw.acpi.reset_video="0"'
    owner: root
    group: wheel
    mode: 0644
    state: absent
  notify:
    - sysctl restart

- name: /etc/sysctl.conf | hw.acpi.sleep_button_state
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^([\s]*)[\#]?([\s]*)hw\.acpi\.sleep_button_state([\s]*)='
    line: 'hw.acpi.sleep_button_state="S3"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

# NOTE(seanc@): There is no reason this is set to 1 other than
# personal preference.
- name: /etc/sysctl.conf | hw.acpi.sleep_delay
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^[\s]*[\#]?[\s]*hw\.acpi\.sleep_delay[\s]*='
    line: 'hw.acpi.sleep_delay="1"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

# NOTE(seanc@): The following options are taken from
# https://www.banym.de/freebsd/install-freebsd-11-on-thinkpad-t420
- name: /etc/rc.conf | T420 services
  sysrc:
    name: "{{ item }}_enable"
    value: "YES"
  with_items:
    - dbus
  notify:
    - dbus start

- name: /etc/rc.conf | performance_cx_lowest
  sysrc:
    name: performance_cx_lowest
    value: "Cmax"

- name: /etc/rc.conf | economy_cx_lowest
  sysrc:
    name: economy_cx_lowest
    value: "Cmax"

- name: /etc/rc.conf | moused_flags
  sysrc:
    name: moused_flags
    value: "-VH"
  notify:
    - moused restart

# NOTE(seanc@): Need to test if this works before removing state=absent
- name: /boot/loader.conf | kern.vty
  lineinfile:
    dest: /boot/loader.conf
    regexp: '^([\s]*)[\#]?([\s]*)kern\.vty([\s]*)='
    line: 'kern.vty="vt"'
    owner: root
    group: wheel
    mode: 0644
    state: absent

- name: /boot/loader.conf | hw.vga.textmode
  lineinfile:
    dest: /boot/loader.conf
    regexp: '^([\s]*)[\#]?([\s]*)hw\.vga\.textmode([\s]*)='
    line: 'hw.vga.textmode="1"'
    owner: root
    group: wheel
    mode: 0644

- name: /etc/sysctl.conf | dev.pcm.0.play.vchans
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^[\s]*[\#]?[\s]*dev\.pcm\.0\.play\.vchans[\s]*='
    line: 'dev.pcm.0.play.vchans="4"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

- name: /etc/sysctl.conf | dev.pcm.0.rec.vchans
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^[\s]*[\#]?[\s]*dev\.pcm\.0\.rec\.vchans[\s]*='
    line: 'dev.pcm.0.rec.vchans="4"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

- name: /etc/sysctl.conf | hw.snd.maxautovchans
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^[\s]*[\#]?[\s]*hw\.snd\.maxautovchans[\s]*='
    line: 'hw.snd.maxautovchans="4"'
    owner: root
    group: wheel
    mode: 0644
  notify:
    - sysctl restart

